### ISSUE TITLE
No colors

### ISSUE THREAD

**Issue by batthias** [jnoortheen/xontrib-broot#1]
Broot doesn't have colors when accessed using `br`.
Tried on MacOS using 256color iTerm2
Colors do work when calling `broot` directly.

**Comment by jnoortheen** [comment]
Yes it happens in Linux terminals as well. It is because xonsh doesn't pass the actual stdout to the alias functions. 
For now, 
you could use `br --color=yes `. Also you could save it as alias/abbrev

**Comment by batthias** [comment]
Thanks for the reply! That's a super easy fix then.

I just edited it in my site-packages and I created a pull request.

**Comment by jnoortheen** [comment]
@batthias Sorry I didn't see any PR. I am adding a commit that adds colors during interactive session.
